// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Filters.proto

package com.tickers.io.protobuf;

public final class FiltersProto {
  private FiltersProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FilterResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.FilterResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string startDate = 3;</code>
     * @return The startDate.
     */
    java.lang.String getStartDate();
    /**
     * <code>string startDate = 3;</code>
     * @return The bytes for startDate.
     */
    com.google.protobuf.ByteString
        getStartDateBytes();

    /**
     * <code>string endDate = 4;</code>
     * @return The endDate.
     */
    java.lang.String getEndDate();
    /**
     * <code>string endDate = 4;</code>
     * @return The bytes for endDate.
     */
    com.google.protobuf.ByteString
        getEndDateBytes();
  }
  /**
   * Protobuf type {@code model.FilterResponse}
   */
  public  static final class FilterResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.FilterResponse)
      FilterResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FilterResponse.newBuilder() to construct.
    private FilterResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FilterResponse() {
      id_ = "";
      name_ = "";
      startDate_ = "";
      endDate_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FilterResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FilterResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              startDate_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              endDate_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tickers.io.protobuf.FiltersProto.internal_static_model_FilterResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tickers.io.protobuf.FiltersProto.internal_static_model_FilterResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tickers.io.protobuf.FiltersProto.FilterResponse.class, com.tickers.io.protobuf.FiltersProto.FilterResponse.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTDATE_FIELD_NUMBER = 3;
    private volatile java.lang.Object startDate_;
    /**
     * <code>string startDate = 3;</code>
     * @return The startDate.
     */
    public java.lang.String getStartDate() {
      java.lang.Object ref = startDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startDate_ = s;
        return s;
      }
    }
    /**
     * <code>string startDate = 3;</code>
     * @return The bytes for startDate.
     */
    public com.google.protobuf.ByteString
        getStartDateBytes() {
      java.lang.Object ref = startDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDDATE_FIELD_NUMBER = 4;
    private volatile java.lang.Object endDate_;
    /**
     * <code>string endDate = 4;</code>
     * @return The endDate.
     */
    public java.lang.String getEndDate() {
      java.lang.Object ref = endDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endDate_ = s;
        return s;
      }
    }
    /**
     * <code>string endDate = 4;</code>
     * @return The bytes for endDate.
     */
    public com.google.protobuf.ByteString
        getEndDateBytes() {
      java.lang.Object ref = endDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getStartDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, startDate_);
      }
      if (!getEndDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, endDate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getStartDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, startDate_);
      }
      if (!getEndDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, endDate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tickers.io.protobuf.FiltersProto.FilterResponse)) {
        return super.equals(obj);
      }
      com.tickers.io.protobuf.FiltersProto.FilterResponse other = (com.tickers.io.protobuf.FiltersProto.FilterResponse) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getStartDate()
          .equals(other.getStartDate())) return false;
      if (!getEndDate()
          .equals(other.getEndDate())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + STARTDATE_FIELD_NUMBER;
      hash = (53 * hash) + getStartDate().hashCode();
      hash = (37 * hash) + ENDDATE_FIELD_NUMBER;
      hash = (53 * hash) + getEndDate().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tickers.io.protobuf.FiltersProto.FilterResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tickers.io.protobuf.FiltersProto.FilterResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tickers.io.protobuf.FiltersProto.FilterResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tickers.io.protobuf.FiltersProto.FilterResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tickers.io.protobuf.FiltersProto.FilterResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tickers.io.protobuf.FiltersProto.FilterResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tickers.io.protobuf.FiltersProto.FilterResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tickers.io.protobuf.FiltersProto.FilterResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tickers.io.protobuf.FiltersProto.FilterResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tickers.io.protobuf.FiltersProto.FilterResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tickers.io.protobuf.FiltersProto.FilterResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tickers.io.protobuf.FiltersProto.FilterResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tickers.io.protobuf.FiltersProto.FilterResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.FilterResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.FilterResponse)
        com.tickers.io.protobuf.FiltersProto.FilterResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tickers.io.protobuf.FiltersProto.internal_static_model_FilterResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tickers.io.protobuf.FiltersProto.internal_static_model_FilterResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tickers.io.protobuf.FiltersProto.FilterResponse.class, com.tickers.io.protobuf.FiltersProto.FilterResponse.Builder.class);
      }

      // Construct using com.tickers.io.protobuf.FiltersProto.FilterResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        startDate_ = "";

        endDate_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tickers.io.protobuf.FiltersProto.internal_static_model_FilterResponse_descriptor;
      }

      @java.lang.Override
      public com.tickers.io.protobuf.FiltersProto.FilterResponse getDefaultInstanceForType() {
        return com.tickers.io.protobuf.FiltersProto.FilterResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.tickers.io.protobuf.FiltersProto.FilterResponse build() {
        com.tickers.io.protobuf.FiltersProto.FilterResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tickers.io.protobuf.FiltersProto.FilterResponse buildPartial() {
        com.tickers.io.protobuf.FiltersProto.FilterResponse result = new com.tickers.io.protobuf.FiltersProto.FilterResponse(this);
        result.id_ = id_;
        result.name_ = name_;
        result.startDate_ = startDate_;
        result.endDate_ = endDate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tickers.io.protobuf.FiltersProto.FilterResponse) {
          return mergeFrom((com.tickers.io.protobuf.FiltersProto.FilterResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tickers.io.protobuf.FiltersProto.FilterResponse other) {
        if (other == com.tickers.io.protobuf.FiltersProto.FilterResponse.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getStartDate().isEmpty()) {
          startDate_ = other.startDate_;
          onChanged();
        }
        if (!other.getEndDate().isEmpty()) {
          endDate_ = other.endDate_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tickers.io.protobuf.FiltersProto.FilterResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tickers.io.protobuf.FiltersProto.FilterResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object startDate_ = "";
      /**
       * <code>string startDate = 3;</code>
       * @return The startDate.
       */
      public java.lang.String getStartDate() {
        java.lang.Object ref = startDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          startDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string startDate = 3;</code>
       * @return The bytes for startDate.
       */
      public com.google.protobuf.ByteString
          getStartDateBytes() {
        java.lang.Object ref = startDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string startDate = 3;</code>
       * @param value The startDate to set.
       * @return This builder for chaining.
       */
      public Builder setStartDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        startDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string startDate = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartDate() {
        
        startDate_ = getDefaultInstance().getStartDate();
        onChanged();
        return this;
      }
      /**
       * <code>string startDate = 3;</code>
       * @param value The bytes for startDate to set.
       * @return This builder for chaining.
       */
      public Builder setStartDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        startDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object endDate_ = "";
      /**
       * <code>string endDate = 4;</code>
       * @return The endDate.
       */
      public java.lang.String getEndDate() {
        java.lang.Object ref = endDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          endDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string endDate = 4;</code>
       * @return The bytes for endDate.
       */
      public com.google.protobuf.ByteString
          getEndDateBytes() {
        java.lang.Object ref = endDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string endDate = 4;</code>
       * @param value The endDate to set.
       * @return This builder for chaining.
       */
      public Builder setEndDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        endDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string endDate = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndDate() {
        
        endDate_ = getDefaultInstance().getEndDate();
        onChanged();
        return this;
      }
      /**
       * <code>string endDate = 4;</code>
       * @param value The bytes for endDate to set.
       * @return This builder for chaining.
       */
      public Builder setEndDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        endDate_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.FilterResponse)
    }

    // @@protoc_insertion_point(class_scope:model.FilterResponse)
    private static final com.tickers.io.protobuf.FiltersProto.FilterResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tickers.io.protobuf.FiltersProto.FilterResponse();
    }

    public static com.tickers.io.protobuf.FiltersProto.FilterResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FilterResponse>
        PARSER = new com.google.protobuf.AbstractParser<FilterResponse>() {
      @java.lang.Override
      public FilterResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FilterResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FilterResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FilterResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tickers.io.protobuf.FiltersProto.FilterResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FiltersResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.FiltersResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .model.FilterResponse content = 1;</code>
     */
    java.util.List<com.tickers.io.protobuf.FiltersProto.FilterResponse> 
        getContentList();
    /**
     * <code>repeated .model.FilterResponse content = 1;</code>
     */
    com.tickers.io.protobuf.FiltersProto.FilterResponse getContent(int index);
    /**
     * <code>repeated .model.FilterResponse content = 1;</code>
     */
    int getContentCount();
    /**
     * <code>repeated .model.FilterResponse content = 1;</code>
     */
    java.util.List<? extends com.tickers.io.protobuf.FiltersProto.FilterResponseOrBuilder> 
        getContentOrBuilderList();
    /**
     * <code>repeated .model.FilterResponse content = 1;</code>
     */
    com.tickers.io.protobuf.FiltersProto.FilterResponseOrBuilder getContentOrBuilder(
        int index);

    /**
     * <code>.model.PageableResponse pageable = 2;</code>
     * @return Whether the pageable field is set.
     */
    boolean hasPageable();
    /**
     * <code>.model.PageableResponse pageable = 2;</code>
     * @return The pageable.
     */
    com.tickers.io.protobuf.GenericProtos.PageableResponse getPageable();
    /**
     * <code>.model.PageableResponse pageable = 2;</code>
     */
    com.tickers.io.protobuf.GenericProtos.PageableResponseOrBuilder getPageableOrBuilder();
  }
  /**
   * Protobuf type {@code model.FiltersResponse}
   */
  public  static final class FiltersResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.FiltersResponse)
      FiltersResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FiltersResponse.newBuilder() to construct.
    private FiltersResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FiltersResponse() {
      content_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FiltersResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FiltersResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                content_ = new java.util.ArrayList<com.tickers.io.protobuf.FiltersProto.FilterResponse>();
                mutable_bitField0_ |= 0x00000001;
              }
              content_.add(
                  input.readMessage(com.tickers.io.protobuf.FiltersProto.FilterResponse.parser(), extensionRegistry));
              break;
            }
            case 18: {
              com.tickers.io.protobuf.GenericProtos.PageableResponse.Builder subBuilder = null;
              if (pageable_ != null) {
                subBuilder = pageable_.toBuilder();
              }
              pageable_ = input.readMessage(com.tickers.io.protobuf.GenericProtos.PageableResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pageable_);
                pageable_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          content_ = java.util.Collections.unmodifiableList(content_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tickers.io.protobuf.FiltersProto.internal_static_model_FiltersResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tickers.io.protobuf.FiltersProto.internal_static_model_FiltersResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tickers.io.protobuf.FiltersProto.FiltersResponse.class, com.tickers.io.protobuf.FiltersProto.FiltersResponse.Builder.class);
    }

    public static final int CONTENT_FIELD_NUMBER = 1;
    private java.util.List<com.tickers.io.protobuf.FiltersProto.FilterResponse> content_;
    /**
     * <code>repeated .model.FilterResponse content = 1;</code>
     */
    public java.util.List<com.tickers.io.protobuf.FiltersProto.FilterResponse> getContentList() {
      return content_;
    }
    /**
     * <code>repeated .model.FilterResponse content = 1;</code>
     */
    public java.util.List<? extends com.tickers.io.protobuf.FiltersProto.FilterResponseOrBuilder> 
        getContentOrBuilderList() {
      return content_;
    }
    /**
     * <code>repeated .model.FilterResponse content = 1;</code>
     */
    public int getContentCount() {
      return content_.size();
    }
    /**
     * <code>repeated .model.FilterResponse content = 1;</code>
     */
    public com.tickers.io.protobuf.FiltersProto.FilterResponse getContent(int index) {
      return content_.get(index);
    }
    /**
     * <code>repeated .model.FilterResponse content = 1;</code>
     */
    public com.tickers.io.protobuf.FiltersProto.FilterResponseOrBuilder getContentOrBuilder(
        int index) {
      return content_.get(index);
    }

    public static final int PAGEABLE_FIELD_NUMBER = 2;
    private com.tickers.io.protobuf.GenericProtos.PageableResponse pageable_;
    /**
     * <code>.model.PageableResponse pageable = 2;</code>
     * @return Whether the pageable field is set.
     */
    public boolean hasPageable() {
      return pageable_ != null;
    }
    /**
     * <code>.model.PageableResponse pageable = 2;</code>
     * @return The pageable.
     */
    public com.tickers.io.protobuf.GenericProtos.PageableResponse getPageable() {
      return pageable_ == null ? com.tickers.io.protobuf.GenericProtos.PageableResponse.getDefaultInstance() : pageable_;
    }
    /**
     * <code>.model.PageableResponse pageable = 2;</code>
     */
    public com.tickers.io.protobuf.GenericProtos.PageableResponseOrBuilder getPageableOrBuilder() {
      return getPageable();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < content_.size(); i++) {
        output.writeMessage(1, content_.get(i));
      }
      if (pageable_ != null) {
        output.writeMessage(2, getPageable());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < content_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, content_.get(i));
      }
      if (pageable_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPageable());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tickers.io.protobuf.FiltersProto.FiltersResponse)) {
        return super.equals(obj);
      }
      com.tickers.io.protobuf.FiltersProto.FiltersResponse other = (com.tickers.io.protobuf.FiltersProto.FiltersResponse) obj;

      if (!getContentList()
          .equals(other.getContentList())) return false;
      if (hasPageable() != other.hasPageable()) return false;
      if (hasPageable()) {
        if (!getPageable()
            .equals(other.getPageable())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getContentCount() > 0) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContentList().hashCode();
      }
      if (hasPageable()) {
        hash = (37 * hash) + PAGEABLE_FIELD_NUMBER;
        hash = (53 * hash) + getPageable().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tickers.io.protobuf.FiltersProto.FiltersResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tickers.io.protobuf.FiltersProto.FiltersResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tickers.io.protobuf.FiltersProto.FiltersResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tickers.io.protobuf.FiltersProto.FiltersResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tickers.io.protobuf.FiltersProto.FiltersResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tickers.io.protobuf.FiltersProto.FiltersResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tickers.io.protobuf.FiltersProto.FiltersResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tickers.io.protobuf.FiltersProto.FiltersResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tickers.io.protobuf.FiltersProto.FiltersResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tickers.io.protobuf.FiltersProto.FiltersResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tickers.io.protobuf.FiltersProto.FiltersResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tickers.io.protobuf.FiltersProto.FiltersResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tickers.io.protobuf.FiltersProto.FiltersResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.FiltersResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.FiltersResponse)
        com.tickers.io.protobuf.FiltersProto.FiltersResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tickers.io.protobuf.FiltersProto.internal_static_model_FiltersResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tickers.io.protobuf.FiltersProto.internal_static_model_FiltersResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tickers.io.protobuf.FiltersProto.FiltersResponse.class, com.tickers.io.protobuf.FiltersProto.FiltersResponse.Builder.class);
      }

      // Construct using com.tickers.io.protobuf.FiltersProto.FiltersResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getContentFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (contentBuilder_ == null) {
          content_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          contentBuilder_.clear();
        }
        if (pageableBuilder_ == null) {
          pageable_ = null;
        } else {
          pageable_ = null;
          pageableBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tickers.io.protobuf.FiltersProto.internal_static_model_FiltersResponse_descriptor;
      }

      @java.lang.Override
      public com.tickers.io.protobuf.FiltersProto.FiltersResponse getDefaultInstanceForType() {
        return com.tickers.io.protobuf.FiltersProto.FiltersResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.tickers.io.protobuf.FiltersProto.FiltersResponse build() {
        com.tickers.io.protobuf.FiltersProto.FiltersResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tickers.io.protobuf.FiltersProto.FiltersResponse buildPartial() {
        com.tickers.io.protobuf.FiltersProto.FiltersResponse result = new com.tickers.io.protobuf.FiltersProto.FiltersResponse(this);
        int from_bitField0_ = bitField0_;
        if (contentBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            content_ = java.util.Collections.unmodifiableList(content_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
        if (pageableBuilder_ == null) {
          result.pageable_ = pageable_;
        } else {
          result.pageable_ = pageableBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tickers.io.protobuf.FiltersProto.FiltersResponse) {
          return mergeFrom((com.tickers.io.protobuf.FiltersProto.FiltersResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tickers.io.protobuf.FiltersProto.FiltersResponse other) {
        if (other == com.tickers.io.protobuf.FiltersProto.FiltersResponse.getDefaultInstance()) return this;
        if (contentBuilder_ == null) {
          if (!other.content_.isEmpty()) {
            if (content_.isEmpty()) {
              content_ = other.content_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureContentIsMutable();
              content_.addAll(other.content_);
            }
            onChanged();
          }
        } else {
          if (!other.content_.isEmpty()) {
            if (contentBuilder_.isEmpty()) {
              contentBuilder_.dispose();
              contentBuilder_ = null;
              content_ = other.content_;
              bitField0_ = (bitField0_ & ~0x00000001);
              contentBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getContentFieldBuilder() : null;
            } else {
              contentBuilder_.addAllMessages(other.content_);
            }
          }
        }
        if (other.hasPageable()) {
          mergePageable(other.getPageable());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tickers.io.protobuf.FiltersProto.FiltersResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tickers.io.protobuf.FiltersProto.FiltersResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.tickers.io.protobuf.FiltersProto.FilterResponse> content_ =
        java.util.Collections.emptyList();
      private void ensureContentIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          content_ = new java.util.ArrayList<com.tickers.io.protobuf.FiltersProto.FilterResponse>(content_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tickers.io.protobuf.FiltersProto.FilterResponse, com.tickers.io.protobuf.FiltersProto.FilterResponse.Builder, com.tickers.io.protobuf.FiltersProto.FilterResponseOrBuilder> contentBuilder_;

      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public java.util.List<com.tickers.io.protobuf.FiltersProto.FilterResponse> getContentList() {
        if (contentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(content_);
        } else {
          return contentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public int getContentCount() {
        if (contentBuilder_ == null) {
          return content_.size();
        } else {
          return contentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public com.tickers.io.protobuf.FiltersProto.FilterResponse getContent(int index) {
        if (contentBuilder_ == null) {
          return content_.get(index);
        } else {
          return contentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public Builder setContent(
          int index, com.tickers.io.protobuf.FiltersProto.FilterResponse value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentIsMutable();
          content_.set(index, value);
          onChanged();
        } else {
          contentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public Builder setContent(
          int index, com.tickers.io.protobuf.FiltersProto.FilterResponse.Builder builderForValue) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.set(index, builderForValue.build());
          onChanged();
        } else {
          contentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public Builder addContent(com.tickers.io.protobuf.FiltersProto.FilterResponse value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentIsMutable();
          content_.add(value);
          onChanged();
        } else {
          contentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public Builder addContent(
          int index, com.tickers.io.protobuf.FiltersProto.FilterResponse value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentIsMutable();
          content_.add(index, value);
          onChanged();
        } else {
          contentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public Builder addContent(
          com.tickers.io.protobuf.FiltersProto.FilterResponse.Builder builderForValue) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.add(builderForValue.build());
          onChanged();
        } else {
          contentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public Builder addContent(
          int index, com.tickers.io.protobuf.FiltersProto.FilterResponse.Builder builderForValue) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.add(index, builderForValue.build());
          onChanged();
        } else {
          contentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public Builder addAllContent(
          java.lang.Iterable<? extends com.tickers.io.protobuf.FiltersProto.FilterResponse> values) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, content_);
          onChanged();
        } else {
          contentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          contentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public Builder removeContent(int index) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.remove(index);
          onChanged();
        } else {
          contentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public com.tickers.io.protobuf.FiltersProto.FilterResponse.Builder getContentBuilder(
          int index) {
        return getContentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public com.tickers.io.protobuf.FiltersProto.FilterResponseOrBuilder getContentOrBuilder(
          int index) {
        if (contentBuilder_ == null) {
          return content_.get(index);  } else {
          return contentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public java.util.List<? extends com.tickers.io.protobuf.FiltersProto.FilterResponseOrBuilder> 
           getContentOrBuilderList() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(content_);
        }
      }
      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public com.tickers.io.protobuf.FiltersProto.FilterResponse.Builder addContentBuilder() {
        return getContentFieldBuilder().addBuilder(
            com.tickers.io.protobuf.FiltersProto.FilterResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public com.tickers.io.protobuf.FiltersProto.FilterResponse.Builder addContentBuilder(
          int index) {
        return getContentFieldBuilder().addBuilder(
            index, com.tickers.io.protobuf.FiltersProto.FilterResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .model.FilterResponse content = 1;</code>
       */
      public java.util.List<com.tickers.io.protobuf.FiltersProto.FilterResponse.Builder> 
           getContentBuilderList() {
        return getContentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tickers.io.protobuf.FiltersProto.FilterResponse, com.tickers.io.protobuf.FiltersProto.FilterResponse.Builder, com.tickers.io.protobuf.FiltersProto.FilterResponseOrBuilder> 
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.tickers.io.protobuf.FiltersProto.FilterResponse, com.tickers.io.protobuf.FiltersProto.FilterResponse.Builder, com.tickers.io.protobuf.FiltersProto.FilterResponseOrBuilder>(
                  content_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }

      private com.tickers.io.protobuf.GenericProtos.PageableResponse pageable_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tickers.io.protobuf.GenericProtos.PageableResponse, com.tickers.io.protobuf.GenericProtos.PageableResponse.Builder, com.tickers.io.protobuf.GenericProtos.PageableResponseOrBuilder> pageableBuilder_;
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       * @return Whether the pageable field is set.
       */
      public boolean hasPageable() {
        return pageableBuilder_ != null || pageable_ != null;
      }
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       * @return The pageable.
       */
      public com.tickers.io.protobuf.GenericProtos.PageableResponse getPageable() {
        if (pageableBuilder_ == null) {
          return pageable_ == null ? com.tickers.io.protobuf.GenericProtos.PageableResponse.getDefaultInstance() : pageable_;
        } else {
          return pageableBuilder_.getMessage();
        }
      }
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       */
      public Builder setPageable(com.tickers.io.protobuf.GenericProtos.PageableResponse value) {
        if (pageableBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pageable_ = value;
          onChanged();
        } else {
          pageableBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       */
      public Builder setPageable(
          com.tickers.io.protobuf.GenericProtos.PageableResponse.Builder builderForValue) {
        if (pageableBuilder_ == null) {
          pageable_ = builderForValue.build();
          onChanged();
        } else {
          pageableBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       */
      public Builder mergePageable(com.tickers.io.protobuf.GenericProtos.PageableResponse value) {
        if (pageableBuilder_ == null) {
          if (pageable_ != null) {
            pageable_ =
              com.tickers.io.protobuf.GenericProtos.PageableResponse.newBuilder(pageable_).mergeFrom(value).buildPartial();
          } else {
            pageable_ = value;
          }
          onChanged();
        } else {
          pageableBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       */
      public Builder clearPageable() {
        if (pageableBuilder_ == null) {
          pageable_ = null;
          onChanged();
        } else {
          pageable_ = null;
          pageableBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       */
      public com.tickers.io.protobuf.GenericProtos.PageableResponse.Builder getPageableBuilder() {
        
        onChanged();
        return getPageableFieldBuilder().getBuilder();
      }
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       */
      public com.tickers.io.protobuf.GenericProtos.PageableResponseOrBuilder getPageableOrBuilder() {
        if (pageableBuilder_ != null) {
          return pageableBuilder_.getMessageOrBuilder();
        } else {
          return pageable_ == null ?
              com.tickers.io.protobuf.GenericProtos.PageableResponse.getDefaultInstance() : pageable_;
        }
      }
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tickers.io.protobuf.GenericProtos.PageableResponse, com.tickers.io.protobuf.GenericProtos.PageableResponse.Builder, com.tickers.io.protobuf.GenericProtos.PageableResponseOrBuilder> 
          getPageableFieldBuilder() {
        if (pageableBuilder_ == null) {
          pageableBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tickers.io.protobuf.GenericProtos.PageableResponse, com.tickers.io.protobuf.GenericProtos.PageableResponse.Builder, com.tickers.io.protobuf.GenericProtos.PageableResponseOrBuilder>(
                  getPageable(),
                  getParentForChildren(),
                  isClean());
          pageable_ = null;
        }
        return pageableBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.FiltersResponse)
    }

    // @@protoc_insertion_point(class_scope:model.FiltersResponse)
    private static final com.tickers.io.protobuf.FiltersProto.FiltersResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tickers.io.protobuf.FiltersProto.FiltersResponse();
    }

    public static com.tickers.io.protobuf.FiltersProto.FiltersResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FiltersResponse>
        PARSER = new com.google.protobuf.AbstractParser<FiltersResponse>() {
      @java.lang.Override
      public FiltersResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FiltersResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FiltersResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FiltersResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tickers.io.protobuf.FiltersProto.FiltersResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_FilterResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_FilterResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_FiltersResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_FiltersResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rFilters.proto\022\005model\032\rGeneric.proto\"N\n" +
      "\016FilterResponse\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(" +
      "\t\022\021\n\tstartDate\030\003 \001(\t\022\017\n\007endDate\030\004 \001(\t\"d\n" +
      "\017FiltersResponse\022&\n\007content\030\001 \003(\0132\025.mode" +
      "l.FilterResponse\022)\n\010pageable\030\002 \001(\0132\027.mod" +
      "el.PageableResponseB\'\n\027com.tickers.io.pr" +
      "otobufB\014FiltersProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tickers.io.protobuf.GenericProtos.getDescriptor(),
        });
    internal_static_model_FilterResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_FilterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_FilterResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "StartDate", "EndDate", });
    internal_static_model_FiltersResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_FiltersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_FiltersResponse_descriptor,
        new java.lang.String[] { "Content", "Pageable", });
    com.tickers.io.protobuf.GenericProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
