// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserSession.proto

package com.tickers.io.protobuf;

public final class UserSessionProtos {
  private UserSessionProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserSessionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.UserSessionResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string user_agent = 2;</code>
     * @return The userAgent.
     */
    java.lang.String getUserAgent();
    /**
     * <code>string user_agent = 2;</code>
     * @return The bytes for userAgent.
     */
    com.google.protobuf.ByteString
        getUserAgentBytes();

    /**
     * <code>string ip = 3;</code>
     * @return The ip.
     */
    java.lang.String getIp();
    /**
     * <code>string ip = 3;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>string expires_at = 4;</code>
     * @return The expiresAt.
     */
    java.lang.String getExpiresAt();
    /**
     * <code>string expires_at = 4;</code>
     * @return The bytes for expiresAt.
     */
    com.google.protobuf.ByteString
        getExpiresAtBytes();

    /**
     * <code>string created_at = 5;</code>
     * @return The createdAt.
     */
    java.lang.String getCreatedAt();
    /**
     * <code>string created_at = 5;</code>
     * @return The bytes for createdAt.
     */
    com.google.protobuf.ByteString
        getCreatedAtBytes();
  }
  /**
   * Protobuf type {@code model.UserSessionResponse}
   */
  public  static final class UserSessionResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.UserSessionResponse)
      UserSessionResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserSessionResponse.newBuilder() to construct.
    private UserSessionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserSessionResponse() {
      id_ = "";
      userAgent_ = "";
      ip_ = "";
      expiresAt_ = "";
      createdAt_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserSessionResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserSessionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userAgent_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              expiresAt_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              createdAt_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tickers.io.protobuf.UserSessionProtos.internal_static_model_UserSessionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tickers.io.protobuf.UserSessionProtos.internal_static_model_UserSessionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.class, com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_AGENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object userAgent_;
    /**
     * <code>string user_agent = 2;</code>
     * @return The userAgent.
     */
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userAgent_ = s;
        return s;
      }
    }
    /**
     * <code>string user_agent = 2;</code>
     * @return The bytes for userAgent.
     */
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 3;
    private volatile java.lang.Object ip_;
    /**
     * <code>string ip = 3;</code>
     * @return The ip.
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 3;</code>
     * @return The bytes for ip.
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRES_AT_FIELD_NUMBER = 4;
    private volatile java.lang.Object expiresAt_;
    /**
     * <code>string expires_at = 4;</code>
     * @return The expiresAt.
     */
    public java.lang.String getExpiresAt() {
      java.lang.Object ref = expiresAt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        expiresAt_ = s;
        return s;
      }
    }
    /**
     * <code>string expires_at = 4;</code>
     * @return The bytes for expiresAt.
     */
    public com.google.protobuf.ByteString
        getExpiresAtBytes() {
      java.lang.Object ref = expiresAt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        expiresAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATED_AT_FIELD_NUMBER = 5;
    private volatile java.lang.Object createdAt_;
    /**
     * <code>string created_at = 5;</code>
     * @return The createdAt.
     */
    public java.lang.String getCreatedAt() {
      java.lang.Object ref = createdAt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdAt_ = s;
        return s;
      }
    }
    /**
     * <code>string created_at = 5;</code>
     * @return The bytes for createdAt.
     */
    public com.google.protobuf.ByteString
        getCreatedAtBytes() {
      java.lang.Object ref = createdAt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getUserAgentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userAgent_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ip_);
      }
      if (!getExpiresAtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, expiresAt_);
      }
      if (!getCreatedAtBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, createdAt_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getUserAgentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userAgent_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ip_);
      }
      if (!getExpiresAtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, expiresAt_);
      }
      if (!getCreatedAtBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, createdAt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse)) {
        return super.equals(obj);
      }
      com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse other = (com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getUserAgent()
          .equals(other.getUserAgent())) return false;
      if (!getIp()
          .equals(other.getIp())) return false;
      if (!getExpiresAt()
          .equals(other.getExpiresAt())) return false;
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + USER_AGENT_FIELD_NUMBER;
      hash = (53 * hash) + getUserAgent().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + EXPIRES_AT_FIELD_NUMBER;
      hash = (53 * hash) + getExpiresAt().hashCode();
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.UserSessionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.UserSessionResponse)
        com.tickers.io.protobuf.UserSessionProtos.UserSessionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tickers.io.protobuf.UserSessionProtos.internal_static_model_UserSessionResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tickers.io.protobuf.UserSessionProtos.internal_static_model_UserSessionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.class, com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.Builder.class);
      }

      // Construct using com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        userAgent_ = "";

        ip_ = "";

        expiresAt_ = "";

        createdAt_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tickers.io.protobuf.UserSessionProtos.internal_static_model_UserSessionResponse_descriptor;
      }

      @java.lang.Override
      public com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse getDefaultInstanceForType() {
        return com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse build() {
        com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse buildPartial() {
        com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse result = new com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse(this);
        result.id_ = id_;
        result.userAgent_ = userAgent_;
        result.ip_ = ip_;
        result.expiresAt_ = expiresAt_;
        result.createdAt_ = createdAt_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse) {
          return mergeFrom((com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse other) {
        if (other == com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getUserAgent().isEmpty()) {
          userAgent_ = other.userAgent_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (!other.getExpiresAt().isEmpty()) {
          expiresAt_ = other.expiresAt_;
          onChanged();
        }
        if (!other.getCreatedAt().isEmpty()) {
          createdAt_ = other.createdAt_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userAgent_ = "";
      /**
       * <code>string user_agent = 2;</code>
       * @return The userAgent.
       */
      public java.lang.String getUserAgent() {
        java.lang.Object ref = userAgent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userAgent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_agent = 2;</code>
       * @return The bytes for userAgent.
       */
      public com.google.protobuf.ByteString
          getUserAgentBytes() {
        java.lang.Object ref = userAgent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userAgent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_agent = 2;</code>
       * @param value The userAgent to set.
       * @return This builder for chaining.
       */
      public Builder setUserAgent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userAgent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_agent = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserAgent() {
        
        userAgent_ = getDefaultInstance().getUserAgent();
        onChanged();
        return this;
      }
      /**
       * <code>string user_agent = 2;</code>
       * @param value The bytes for userAgent to set.
       * @return This builder for chaining.
       */
      public Builder setUserAgentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userAgent_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>string ip = 3;</code>
       * @return The ip.
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip = 3;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 3;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 3;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object expiresAt_ = "";
      /**
       * <code>string expires_at = 4;</code>
       * @return The expiresAt.
       */
      public java.lang.String getExpiresAt() {
        java.lang.Object ref = expiresAt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          expiresAt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string expires_at = 4;</code>
       * @return The bytes for expiresAt.
       */
      public com.google.protobuf.ByteString
          getExpiresAtBytes() {
        java.lang.Object ref = expiresAt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          expiresAt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string expires_at = 4;</code>
       * @param value The expiresAt to set.
       * @return This builder for chaining.
       */
      public Builder setExpiresAt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        expiresAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string expires_at = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearExpiresAt() {
        
        expiresAt_ = getDefaultInstance().getExpiresAt();
        onChanged();
        return this;
      }
      /**
       * <code>string expires_at = 4;</code>
       * @param value The bytes for expiresAt to set.
       * @return This builder for chaining.
       */
      public Builder setExpiresAtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        expiresAt_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object createdAt_ = "";
      /**
       * <code>string created_at = 5;</code>
       * @return The createdAt.
       */
      public java.lang.String getCreatedAt() {
        java.lang.Object ref = createdAt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          createdAt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string created_at = 5;</code>
       * @return The bytes for createdAt.
       */
      public com.google.protobuf.ByteString
          getCreatedAtBytes() {
        java.lang.Object ref = createdAt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          createdAt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string created_at = 5;</code>
       * @param value The createdAt to set.
       * @return This builder for chaining.
       */
      public Builder setCreatedAt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        createdAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string created_at = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreatedAt() {
        
        createdAt_ = getDefaultInstance().getCreatedAt();
        onChanged();
        return this;
      }
      /**
       * <code>string created_at = 5;</code>
       * @param value The bytes for createdAt to set.
       * @return This builder for chaining.
       */
      public Builder setCreatedAtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        createdAt_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.UserSessionResponse)
    }

    // @@protoc_insertion_point(class_scope:model.UserSessionResponse)
    private static final com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse();
    }

    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserSessionResponse>
        PARSER = new com.google.protobuf.AbstractParser<UserSessionResponse>() {
      @java.lang.Override
      public UserSessionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserSessionResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserSessionResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserSessionResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserSessionsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.UserSessionsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .model.UserSessionResponse content = 1;</code>
     */
    java.util.List<com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse> 
        getContentList();
    /**
     * <code>repeated .model.UserSessionResponse content = 1;</code>
     */
    com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse getContent(int index);
    /**
     * <code>repeated .model.UserSessionResponse content = 1;</code>
     */
    int getContentCount();
    /**
     * <code>repeated .model.UserSessionResponse content = 1;</code>
     */
    java.util.List<? extends com.tickers.io.protobuf.UserSessionProtos.UserSessionResponseOrBuilder> 
        getContentOrBuilderList();
    /**
     * <code>repeated .model.UserSessionResponse content = 1;</code>
     */
    com.tickers.io.protobuf.UserSessionProtos.UserSessionResponseOrBuilder getContentOrBuilder(
        int index);

    /**
     * <code>.model.PageableResponse pageable = 2;</code>
     * @return Whether the pageable field is set.
     */
    boolean hasPageable();
    /**
     * <code>.model.PageableResponse pageable = 2;</code>
     * @return The pageable.
     */
    com.tickers.io.protobuf.GenericProtos.PageableResponse getPageable();
    /**
     * <code>.model.PageableResponse pageable = 2;</code>
     */
    com.tickers.io.protobuf.GenericProtos.PageableResponseOrBuilder getPageableOrBuilder();
  }
  /**
   * Protobuf type {@code model.UserSessionsResponse}
   */
  public  static final class UserSessionsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.UserSessionsResponse)
      UserSessionsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserSessionsResponse.newBuilder() to construct.
    private UserSessionsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserSessionsResponse() {
      content_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserSessionsResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserSessionsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                content_ = new java.util.ArrayList<com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse>();
                mutable_bitField0_ |= 0x00000001;
              }
              content_.add(
                  input.readMessage(com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.parser(), extensionRegistry));
              break;
            }
            case 18: {
              com.tickers.io.protobuf.GenericProtos.PageableResponse.Builder subBuilder = null;
              if (pageable_ != null) {
                subBuilder = pageable_.toBuilder();
              }
              pageable_ = input.readMessage(com.tickers.io.protobuf.GenericProtos.PageableResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pageable_);
                pageable_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          content_ = java.util.Collections.unmodifiableList(content_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tickers.io.protobuf.UserSessionProtos.internal_static_model_UserSessionsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tickers.io.protobuf.UserSessionProtos.internal_static_model_UserSessionsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse.class, com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse.Builder.class);
    }

    public static final int CONTENT_FIELD_NUMBER = 1;
    private java.util.List<com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse> content_;
    /**
     * <code>repeated .model.UserSessionResponse content = 1;</code>
     */
    public java.util.List<com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse> getContentList() {
      return content_;
    }
    /**
     * <code>repeated .model.UserSessionResponse content = 1;</code>
     */
    public java.util.List<? extends com.tickers.io.protobuf.UserSessionProtos.UserSessionResponseOrBuilder> 
        getContentOrBuilderList() {
      return content_;
    }
    /**
     * <code>repeated .model.UserSessionResponse content = 1;</code>
     */
    public int getContentCount() {
      return content_.size();
    }
    /**
     * <code>repeated .model.UserSessionResponse content = 1;</code>
     */
    public com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse getContent(int index) {
      return content_.get(index);
    }
    /**
     * <code>repeated .model.UserSessionResponse content = 1;</code>
     */
    public com.tickers.io.protobuf.UserSessionProtos.UserSessionResponseOrBuilder getContentOrBuilder(
        int index) {
      return content_.get(index);
    }

    public static final int PAGEABLE_FIELD_NUMBER = 2;
    private com.tickers.io.protobuf.GenericProtos.PageableResponse pageable_;
    /**
     * <code>.model.PageableResponse pageable = 2;</code>
     * @return Whether the pageable field is set.
     */
    public boolean hasPageable() {
      return pageable_ != null;
    }
    /**
     * <code>.model.PageableResponse pageable = 2;</code>
     * @return The pageable.
     */
    public com.tickers.io.protobuf.GenericProtos.PageableResponse getPageable() {
      return pageable_ == null ? com.tickers.io.protobuf.GenericProtos.PageableResponse.getDefaultInstance() : pageable_;
    }
    /**
     * <code>.model.PageableResponse pageable = 2;</code>
     */
    public com.tickers.io.protobuf.GenericProtos.PageableResponseOrBuilder getPageableOrBuilder() {
      return getPageable();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < content_.size(); i++) {
        output.writeMessage(1, content_.get(i));
      }
      if (pageable_ != null) {
        output.writeMessage(2, getPageable());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < content_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, content_.get(i));
      }
      if (pageable_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPageable());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse)) {
        return super.equals(obj);
      }
      com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse other = (com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse) obj;

      if (!getContentList()
          .equals(other.getContentList())) return false;
      if (hasPageable() != other.hasPageable()) return false;
      if (hasPageable()) {
        if (!getPageable()
            .equals(other.getPageable())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getContentCount() > 0) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContentList().hashCode();
      }
      if (hasPageable()) {
        hash = (37 * hash) + PAGEABLE_FIELD_NUMBER;
        hash = (53 * hash) + getPageable().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.UserSessionsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.UserSessionsResponse)
        com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tickers.io.protobuf.UserSessionProtos.internal_static_model_UserSessionsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tickers.io.protobuf.UserSessionProtos.internal_static_model_UserSessionsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse.class, com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse.Builder.class);
      }

      // Construct using com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getContentFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (contentBuilder_ == null) {
          content_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          contentBuilder_.clear();
        }
        if (pageableBuilder_ == null) {
          pageable_ = null;
        } else {
          pageable_ = null;
          pageableBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tickers.io.protobuf.UserSessionProtos.internal_static_model_UserSessionsResponse_descriptor;
      }

      @java.lang.Override
      public com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse getDefaultInstanceForType() {
        return com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse build() {
        com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse buildPartial() {
        com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse result = new com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse(this);
        int from_bitField0_ = bitField0_;
        if (contentBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            content_ = java.util.Collections.unmodifiableList(content_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
        if (pageableBuilder_ == null) {
          result.pageable_ = pageable_;
        } else {
          result.pageable_ = pageableBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse) {
          return mergeFrom((com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse other) {
        if (other == com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse.getDefaultInstance()) return this;
        if (contentBuilder_ == null) {
          if (!other.content_.isEmpty()) {
            if (content_.isEmpty()) {
              content_ = other.content_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureContentIsMutable();
              content_.addAll(other.content_);
            }
            onChanged();
          }
        } else {
          if (!other.content_.isEmpty()) {
            if (contentBuilder_.isEmpty()) {
              contentBuilder_.dispose();
              contentBuilder_ = null;
              content_ = other.content_;
              bitField0_ = (bitField0_ & ~0x00000001);
              contentBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getContentFieldBuilder() : null;
            } else {
              contentBuilder_.addAllMessages(other.content_);
            }
          }
        }
        if (other.hasPageable()) {
          mergePageable(other.getPageable());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse> content_ =
        java.util.Collections.emptyList();
      private void ensureContentIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          content_ = new java.util.ArrayList<com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse>(content_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse, com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.Builder, com.tickers.io.protobuf.UserSessionProtos.UserSessionResponseOrBuilder> contentBuilder_;

      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public java.util.List<com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse> getContentList() {
        if (contentBuilder_ == null) {
          return java.util.Collections.unmodifiableList(content_);
        } else {
          return contentBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public int getContentCount() {
        if (contentBuilder_ == null) {
          return content_.size();
        } else {
          return contentBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse getContent(int index) {
        if (contentBuilder_ == null) {
          return content_.get(index);
        } else {
          return contentBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public Builder setContent(
          int index, com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentIsMutable();
          content_.set(index, value);
          onChanged();
        } else {
          contentBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public Builder setContent(
          int index, com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.Builder builderForValue) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.set(index, builderForValue.build());
          onChanged();
        } else {
          contentBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public Builder addContent(com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentIsMutable();
          content_.add(value);
          onChanged();
        } else {
          contentBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public Builder addContent(
          int index, com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentIsMutable();
          content_.add(index, value);
          onChanged();
        } else {
          contentBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public Builder addContent(
          com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.Builder builderForValue) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.add(builderForValue.build());
          onChanged();
        } else {
          contentBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public Builder addContent(
          int index, com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.Builder builderForValue) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.add(index, builderForValue.build());
          onChanged();
        } else {
          contentBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public Builder addAllContent(
          java.lang.Iterable<? extends com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse> values) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, content_);
          onChanged();
        } else {
          contentBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          contentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public Builder removeContent(int index) {
        if (contentBuilder_ == null) {
          ensureContentIsMutable();
          content_.remove(index);
          onChanged();
        } else {
          contentBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.Builder getContentBuilder(
          int index) {
        return getContentFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public com.tickers.io.protobuf.UserSessionProtos.UserSessionResponseOrBuilder getContentOrBuilder(
          int index) {
        if (contentBuilder_ == null) {
          return content_.get(index);  } else {
          return contentBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public java.util.List<? extends com.tickers.io.protobuf.UserSessionProtos.UserSessionResponseOrBuilder> 
           getContentOrBuilderList() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(content_);
        }
      }
      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.Builder addContentBuilder() {
        return getContentFieldBuilder().addBuilder(
            com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.Builder addContentBuilder(
          int index) {
        return getContentFieldBuilder().addBuilder(
            index, com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .model.UserSessionResponse content = 1;</code>
       */
      public java.util.List<com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.Builder> 
           getContentBuilderList() {
        return getContentFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse, com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.Builder, com.tickers.io.protobuf.UserSessionProtos.UserSessionResponseOrBuilder> 
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse, com.tickers.io.protobuf.UserSessionProtos.UserSessionResponse.Builder, com.tickers.io.protobuf.UserSessionProtos.UserSessionResponseOrBuilder>(
                  content_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }

      private com.tickers.io.protobuf.GenericProtos.PageableResponse pageable_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tickers.io.protobuf.GenericProtos.PageableResponse, com.tickers.io.protobuf.GenericProtos.PageableResponse.Builder, com.tickers.io.protobuf.GenericProtos.PageableResponseOrBuilder> pageableBuilder_;
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       * @return Whether the pageable field is set.
       */
      public boolean hasPageable() {
        return pageableBuilder_ != null || pageable_ != null;
      }
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       * @return The pageable.
       */
      public com.tickers.io.protobuf.GenericProtos.PageableResponse getPageable() {
        if (pageableBuilder_ == null) {
          return pageable_ == null ? com.tickers.io.protobuf.GenericProtos.PageableResponse.getDefaultInstance() : pageable_;
        } else {
          return pageableBuilder_.getMessage();
        }
      }
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       */
      public Builder setPageable(com.tickers.io.protobuf.GenericProtos.PageableResponse value) {
        if (pageableBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pageable_ = value;
          onChanged();
        } else {
          pageableBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       */
      public Builder setPageable(
          com.tickers.io.protobuf.GenericProtos.PageableResponse.Builder builderForValue) {
        if (pageableBuilder_ == null) {
          pageable_ = builderForValue.build();
          onChanged();
        } else {
          pageableBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       */
      public Builder mergePageable(com.tickers.io.protobuf.GenericProtos.PageableResponse value) {
        if (pageableBuilder_ == null) {
          if (pageable_ != null) {
            pageable_ =
              com.tickers.io.protobuf.GenericProtos.PageableResponse.newBuilder(pageable_).mergeFrom(value).buildPartial();
          } else {
            pageable_ = value;
          }
          onChanged();
        } else {
          pageableBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       */
      public Builder clearPageable() {
        if (pageableBuilder_ == null) {
          pageable_ = null;
          onChanged();
        } else {
          pageable_ = null;
          pageableBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       */
      public com.tickers.io.protobuf.GenericProtos.PageableResponse.Builder getPageableBuilder() {
        
        onChanged();
        return getPageableFieldBuilder().getBuilder();
      }
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       */
      public com.tickers.io.protobuf.GenericProtos.PageableResponseOrBuilder getPageableOrBuilder() {
        if (pageableBuilder_ != null) {
          return pageableBuilder_.getMessageOrBuilder();
        } else {
          return pageable_ == null ?
              com.tickers.io.protobuf.GenericProtos.PageableResponse.getDefaultInstance() : pageable_;
        }
      }
      /**
       * <code>.model.PageableResponse pageable = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.tickers.io.protobuf.GenericProtos.PageableResponse, com.tickers.io.protobuf.GenericProtos.PageableResponse.Builder, com.tickers.io.protobuf.GenericProtos.PageableResponseOrBuilder> 
          getPageableFieldBuilder() {
        if (pageableBuilder_ == null) {
          pageableBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.tickers.io.protobuf.GenericProtos.PageableResponse, com.tickers.io.protobuf.GenericProtos.PageableResponse.Builder, com.tickers.io.protobuf.GenericProtos.PageableResponseOrBuilder>(
                  getPageable(),
                  getParentForChildren(),
                  isClean());
          pageable_ = null;
        }
        return pageableBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.UserSessionsResponse)
    }

    // @@protoc_insertion_point(class_scope:model.UserSessionsResponse)
    private static final com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse();
    }

    public static com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserSessionsResponse>
        PARSER = new com.google.protobuf.AbstractParser<UserSessionsResponse>() {
      @java.lang.Override
      public UserSessionsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserSessionsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserSessionsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserSessionsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tickers.io.protobuf.UserSessionProtos.UserSessionsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_UserSessionResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_UserSessionResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_UserSessionsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_UserSessionsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021UserSession.proto\022\005model\032\rGeneric.prot" +
      "o\"i\n\023UserSessionResponse\022\n\n\002id\030\001 \001(\t\022\022\n\n" +
      "user_agent\030\002 \001(\t\022\n\n\002ip\030\003 \001(\t\022\022\n\nexpires_" +
      "at\030\004 \001(\t\022\022\n\ncreated_at\030\005 \001(\t\"n\n\024UserSess" +
      "ionsResponse\022+\n\007content\030\001 \003(\0132\032.model.Us" +
      "erSessionResponse\022)\n\010pageable\030\002 \001(\0132\027.mo" +
      "del.PageableResponseB,\n\027com.tickers.io.p" +
      "rotobufB\021UserSessionProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tickers.io.protobuf.GenericProtos.getDescriptor(),
        });
    internal_static_model_UserSessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_UserSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_UserSessionResponse_descriptor,
        new java.lang.String[] { "Id", "UserAgent", "Ip", "ExpiresAt", "CreatedAt", });
    internal_static_model_UserSessionsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_UserSessionsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_UserSessionsResponse_descriptor,
        new java.lang.String[] { "Content", "Pageable", });
    com.tickers.io.protobuf.GenericProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
